<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.SQSEvents" />
        <PackageReference Include="AWSSDK.DynamoDBv2" />
        <PackageReference Include="AWSSDK.S3" />
        <PackageReference Include="AWSSDK.SQS" />

        <PackageReference Include="FluentValidation" />

        <PackageReference Include="LocalStack.Client" />

        <PackageReference Include="Microsoft.Extensions.Options" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />

        <PackageReference Include="OneOf" />
        <PackageReference Include="OneOf.SourceGenerator" />
    </ItemGroup>

</Project>