<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(DefaultTargetFramework)</TargetFramework>

        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <IsAspireSharedProject>true</IsAspireSharedProject>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>

        <PackageReference Include="AWS.Messaging.Telemetry.OpenTelemetry"/>

        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
        <PackageReference Include="OpenTelemetry.Extensions.Hosting"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AWS"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.AWSLambda"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Http"/>
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime"/>

        <PackageReference Include="Microsoft.Extensions.Http.Resilience"/>
        <PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Dns"/>

        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Extensions.Hosting"/>
        <PackageReference Include="Serilog.Settings.Configuration"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
        <PackageReference Include="Serilog.Sinks.OpenTelemetry"/>
    </ItemGroup>

</Project>