<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
        <!--        <AWSProjectType>Lambda</AWSProjectType>-->
        <AssemblyName>bootstrap</AssemblyName>
        <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <!-- Generate Native AOT image during publishing to improve cold start time. -->
        <PublishAot>true</PublishAot> <!-- Disabled for regular Lambda testing -->
        <!-- StripSymbols tells the compiler to strip debugging symbols from the final executable if we're on Linux and put them into their own file.
    This will greatly reduce the final executable's size.-->
        <StripSymbols>true</StripSymbols>
        <!-- TrimMode partial will only trim assemblies marked as trimmable. To reduce package size make all assemblies trimmable and set TrimMode to full.
    If there are trim warnings during build, you can hit errors at runtime.-->
        <TrimMode>partial</TrimMode>
    </PropertyGroup>
    <!--
    When publishing Lambda functions for ARM64 to the provided.al2 runtime a newer version of libicu needs to be included
    in the deployment bundle because .NET requires a newer version of libicu then is preinstalled with Amazon Linux 2.
    -->
    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">
        <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="72.1.0.3"/>
        <PackageReference Include="Microsoft.ICU.ICU4C.Runtime"/>
    </ItemGroup>
    <ItemGroup>
        <TrimmerRootDescriptor Include="ILLink.Descriptors.xml"/>
    </ItemGroup>
    <ItemGroup>
        <None Remove="response.json"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Amazon.Lambda.Core"/>
        <PackageReference Include="Amazon.Lambda.RuntimeSupport"/>
        <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson"/>

        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>

        <PackageReference Include="LocalStack.Client"/>
        <PackageReference Include="LocalStack.Client.Extensions"/>

        <PackageReference Include="Microsoft.Extensions.Configuration.Binder"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
        <PackageReference Include="Microsoft.Extensions.Logging"/>
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions"/>

        <PackageReference Include="Serilog"/>
        <PackageReference Include="Serilog.Extensions.Logging"/>
        <PackageReference Include="Serilog.Settings.Configuration"/>
        <PackageReference Include="Serilog.Sinks.Console"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\LocalStack.Core\LocalStack.Core.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <None Update="appsettings.Development.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <DependentUpon>appsettings.json</DependentUpon>
        </None>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.Production.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
            <DependentUpon>appsettings.json</DependentUpon>
        </None>
    </ItemGroup>

</Project>